nass_api_key: "your-nass-api-key"

industry_sales:
    url: "https://quickstats.nass.usda.gov/api/api_GET/"
    params: 
        commodity_desc: "FERTILIZER"
        year__GE: "2010"

economic_indicators:
    url: "https://quickstats.nass.usda.gov/api/api_GET/"
    indicators: 
        - "NY.GDP.MKTP.CD"  # GDP
        - "FR.INR.RINR"     # Real Interest Rate
